### PR TITLE
Made My Loans and Holds the same size

### PR DESCRIPTION
**Pull request by jonahcrowlinson**
Issue #277 I think should be fixed with this pull request. I think that this is all that needs to be changed for these to be the same size - very similar code to the _appointments_ page,

### CODE REVIEW

**Comment by rkim00** [comment]
@jonahcrowlinson Thanks for your contribution and welcome to Circulate!

Looks like you left the "Checked-out Items" header as an h3 tag—do you think it should be an h2 as well, or should it stay as an h3?

**Comment by jonahcrowlinson** [comment]
> @jonahcrowlinson Thanks for your contribution and welcome to Circulate!
> 
> Looks like you left the "Checked-out Items" header as an h3 tag—do you think it should be an h2 as well, or should it stay as an h3?

I copied the code on the appointments page as that is what #277 said it should be similar to. They were both `<h3>` tags.

**Comment by rkim00** [comment]
I think the dates on the Appointments page (https://circulate-staging.herokuapp.com/appointments) are h2 tags, aren't they? Can we make them h2? I think that's probably better HTML. I know it's wrong on pages like (https://circulate-staging.herokuapp.com/appointments/new) -- we should probably write an issue to fix those as well.

**Comment by jonahcrowlinson** [comment]
They're definitely `<h2>` on the _appointments_ page - should I create another issue or add another commit to the pull request changing the tags on the appointments page?

**Comment by rkim00** [comment]
If you'd like to add another commit changing them on the "Schedule An Appointment" page (https://circulate-staging.herokuapp.com/appointments/new) that would be great. I can't think of a reason why those should be h3 tags there. Thanks!

**Comment by jonahcrowlinson** [comment]
As far as I can see, in _appointments_ the headings are already `h3`. Or do you mean lines 7-8 which I can't tell what are meant to say as they are ERB tags? 
I'm also looking at the latest `development` branch in case you are looking at a different branch?

**Comment by rkim00** [comment]
There are two different appointments pages here.

On the Appointments page (https://circulate-staging.herokuapp.com/appointments) the tags are currently h2. This is correct.

On the "Schedule An Appointment" page (https://circulate-staging.herokuapp.com/appointments/new) the tags are currently h3. This is incorrect. They should be h2. I think those tags are probably found in app/views/appointments/_form.html.erb .

Does that clear things up? If not, when you're referring to _appointments_ and lines 7-8, can you tell me what URL or file you're referring to?

**Comment by jonahcrowlinson** [comment]
Alright - I must have gotten super confused before but I think I have solved it. I have changed all the `h3` tags in the following pages to `h2` tags:

- [appointments/index](https://circulate-staging.herokuapp.com/appointments)
- [appointments/new](https://circulate-staging.herokuapp.com/appointments/new)
- [members/loans](https://circulate-staging.herokuapp.com/members/loans)

**Comment by rkim00** [comment]
Okay, thanks! But I think the h3 tags in appointments/index actually should stay h3 tags, since they come under the h2 tags that are the dates. The other h3 tags I think should be changed, as you seem to have done. Does that make sense? Let me know if I can clarify anything.

**Comment by jonahcrowlinson** [comment]
Ok - I think I have done that. I don't know what my brain was doing this morning!

**Comment by rkim00** [comment]
Cool. Thanks for your work and for hanging in there!

**Comment by jonahcrowlinson** [comment]
No problem! Same goes to you!

**Review by jim — APPROVED** [review]
These changes look good!

If you have a chance to merge in the `development` branch to resolve the merge conflicts, @jonahcrowlinson, that would be great! If not I can do it when I merge this in later.

Thanks for working through this, folks.

**Pull request merged**
