### PR TITLE
Remove local variable `show_password_inputs`

### PR DESCRIPTION
**Pull request by pramod-wdo**
# What it does

- Fix https://github.com/rubyforgood/circulate/issues/650

# Why it is important

_Make a case for merging this work. This might include linking to a relevant issue.

# UI Change Screenshot

_If this PR makes a change to the UI put a screenshot here. If you have before and after screenshots please add these._

# Implementation notes

* _Anything notable about the technical approach you took.

* _Any open questions you have about the PR or areas where you'd like specific feedback.

# Your bandwidth for additional changes to this PR

_Please choose one of the following to help the project maintainers provide the appropriate level of support:_

- [x] I have the time and interest to make additional changes to this PR based on feedback.
- [ ] I am interested in feedback but don't need to make the changes myself.
- [ ] I don't have time or interest in making additional changes to this work.
- [ ] Other or not sure (please describe):

### CODE REVIEW

**Comment by pjsier** [comment]
@jim can I get permissions to approve running workflows? The CircleCI jobs may just be flaky tests, but I want to see if GitHub Actions fails too

**Comment by jim** [comment]
@pjsier Can you see if you have access now? You are a "maintainer" on the repo now and should be able to. Thanks!

**Comment by pjsier** [comment]
@jim works now, thanks!

**Review by pjsier — APPROVED** [review]
This looks good to go! There might be some occasional issues with the tests unrelated to this PR, heads up @jim

**Pull request merged**
