### PR TITLE
Add member/user associations and roles to users

### PR DESCRIPTION
**Pull request by britth**
Adding member access privileges through Member instances. Adds member, admin, and staff roles.

Co-authored by @robbkidd @amygurski @britth @cflipse @cjilbert504

### CODE REVIEW

**Review by amygurski — APPROVED** [review]
LGTM 🍦

**Comment by cflipse** [comment]
https://memegenerator.net/img/instances/73671443/and-i-helped.jpg

**Review by robbkidd — APPROVED** [review]
🚀 🍰 

tenor-208992674

**Comment by cjilbert504** [comment]
👍👍👍

**Review by jim — APPROVED** [review]
Looks great!

**Pull request merged**
