### PR TITLE
Implement item addition to appointment

### PR DESCRIPTION
**Pull request by ghaydarov**
This adds a form to appointment page to add a new item to it. 

add-item-to-checkout

### CODE REVIEW

**Comment by terryfinn** [comment]
I am working on refactoring this, and adding an simple lookup form. Right now you would have to know the actual database id of the item for this to work.

**Comment by terryfinn** [comment]
I pushed up some additions. I would like to help find a good way of searching items, but this seems to be a reasonably simple option for now. We are just using a datalist for the input. This allows for some fuzzy searching of items by the item number and or the name of the item.

**Comment by ghaydarov** [comment]
This looks great to me. Made a small change where I passed wrong member and a wording change.

This will make it convenient to add items to appointment. Great job on this!

**Review by jim — APPROVED** [review]
This looks great, folks!

**Pull request merged**
