### PR TITLE
Fail more gracefully when no appointments are present

### PR DESCRIPTION
**Pull request by ps9793**
Hey,
Just added a div which will show a message telling the user that there are no scheduled appointments when the variable `@appointments` is blank

#342

### CODE REVIEW

**Comment by ps9793** [comment]
The failure doesn't seem to be related to the changes I made, still I am not entirely sure.

Can you please check once and let me know

**Comment by rkim00** [comment]
I'm re-running the tests... we've seen these errors before. Hopefully they'll pass when I re-run.

**Comment by ps9793** [comment]
Ok thanks

**Comment by ps9793** [comment]
Tests passed.
Thanks for the help @rkim00

**Review by jim — APPROVED** [review]
This is a nice improvement. Thanks!

**Pull request merged**
